#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu

sudo apt-get update -y

curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.13.2-amd64.deb

sudo dpkg -i filebeat-7.13.2-amd64.deb

filebeat setup -e

sudo service filebeat start