#!/bin/bash

set -eu
set -o xtrace

if [ "$DISTRO_NAME" == "centos" ]; then
    dnf install -y dnf-plugins-core centos-release-nfv-common
    # REVISIT(cgoncalves): replace arch if-else + GPG with release RPM once available
    if [[ "$ARCH" =~ (aarch64|arm64) ]]; then
        yum_arch=aarch64
    elif [[ "$ARCH" =~ (ppc64le|ppc64el) ]]; then
        yum_arch=ppc64le
    elif [[ "$ARCH" =~ (x86_64|amd64) ]]; then
        yum_arch=x86_64
    else
        echo "ERROR: Unsupported architecture $ARCH"
        exit 1
    fi
    echo -e "sudo apt update -y"
    echo -e   " curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.13.2-amd64.deb"
    echo -e  "sudo dpkg -i filebeat-7.13.2-amd64.deb"
fi
